[package]
name = "toml_edit"
version = "0.1.3"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["toml"]
categories = ["encoding", "parser-implementations", "parsing"]
description = "Yet another format-preserving TOML parser."
authors = ["Andronik Ordian <write@reusable.software>"]
repository = "https://github.com/ordian/toml_edit"
documentation = "https://docs.rs/toml_edit"

[badges]
travis-ci = { repository = "ordian/toml_edit" }
appveyor = { repository = "ordian/toml_edit" }

[dependencies]
chrono = "0.4.6"
linked-hash-map = "0.5.1"
combine = "3.5.1"

[dev-dependencies]
serde_json = "1.0.27"

[profile.dev]
opt-level = 1

[features]
default = []
clippy = []
