[package]
name = "toml_edit"
version = "0.2.0"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["toml"]
categories = ["encoding", "parser-implementations", "parsing"]
description = "Yet another format-preserving TOML parser."
authors = ["Andronik Ordian <write@reusable.software>"]
repository = "https://github.com/ordian/toml_edit"
documentation = "https://docs.rs/toml_edit"
edition = "2018"

[dependencies]
chrono = "0.4.10"
linked-hash-map = "0.5.2"
combine = "4.5.2"

[dev-dependencies]
serde_json = "1.0.44"
pretty_assertions = "0.7.1"

[profile.dev]
opt-level = 1
